### ISSUE TITLE
mp3文件的采样率必须24000吗？

### ISSUE THREAD

**Issue by 976112643** [fishCoder/Silk_v3_decoder#1]
使用其他mp3音频文件，比如44000采样率 ，转换成skill文件后，声音就失真了，变成慢放的了

**Comment by fishCoder** [comment]
不是必须  因为我转的是微信的语音 所以就hardcode了

**Comment by 976112643** [comment]
居然回复了，感谢大佬
那如果我这边是想要把其他采样率的mp3文件转换成silk格式需要如何调整，我现在尝试设置API_fs_Hz但似乎没有效果，输出的还是慢放的时长对不上

**Comment by fishCoder** [comment]
API_fs_Hz  targetRate_bps    两个都改一下

**Comment by zhangruiyu** [comment]
老哥  能加个采样率参数吗  老哥 你开个捐赠行不

**Comment by zhangruiyu** [comment]
> 居然回复了，感谢大佬
> 那如果我这边是想要把其他采样率的mp3文件转换成silk格式需要如何调整，我现在尝试设置API_fs_Hz但似乎没有效果，输出的还是慢放的时长对不上

老哥 你这边成了吗  我这边改mp3转silk 默认24000也是慢放  改成44000, 44100直接没声音了
