### ISSUE TITLE
老哥 能加个采样率参数吗 老哥 你开个捐赠行不

### ISSUE THREAD

**Issue by zhangruiyu** [fishCoder/Silk_v3_decoder#4]
老哥 能加个采样率参数吗 老哥 你开个捐赠行不

**Comment by fishCoder** [comment]
👌 我看看哈

**Comment by zhangruiyu** [comment]
0-0谢谢 嘿嘿 老哥 你贴个捐赠码

**Comment by zhangruiyu** [comment]
0--0老哥 我看你更新了 可是现在是拉不下来的  我建了个新项目也是这样
![image](https://user-images.githubusercontent.com/10591822/82134264-b9b54580-9828-11ea-905f-14c5f28bfc9b.png)

**Comment by zhangruiyu** [comment]
老哥 在不在

**Comment by fishCoder** [comment]
这错误提示我也不看懂什么原因 怀疑cmake编译出错了

**Comment by zhangruiyu** [comment]
那你那边可以依赖成功吗 我这边新建项目也是失败的

**Comment by fishCoder** [comment]
你把详细的构建日志发一下

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/82172205-21889080-98fc-11ea-85ca-977dbca4ca32.png)

**Comment by zhangruiyu** [comment]
感觉像是美发部一样...

**Comment by fishCoder** [comment]
发布的时候失败了又重新上传了，还是不行。我上传了一个新版本
implementation 'com.fulongbin.silk_v3_decoder:decoder:0.9.11'

**Comment by zhangruiyu** [comment]
0-0谢谢老哥 可有依赖成功了

**Comment by zhangruiyu** [comment]
老哥 我发现从'com.fulongbin.silk_v3_decoder:decoder:0.9.8'更新到0.9.11后MP3转silk没有声音 我反复试过,采样我也换成了不行

**Comment by fishCoder** [comment]
是这样 我只用调用c库只能转换格式，不能调整采样率。现在新加的设置采样率其实是指输入音频的采样率。要想更多自由度还是建议使用ffmpeg

**Comment by zhangruiyu** [comment]
目前 Silk.convertSilkToMp3(path, newPath,44100) 这样转化出来的是播放不了的  44100是转出来的mp3采样

**Comment by zhangruiyu** [comment]
Silk.convertMp3ToSilk(path, newPath,44100) 也不行 ,silk没法播放的,mp3的采样是44100 我这边ffmpeg看了
